name: "[CI] Deploy Terraform stacks to Dev"
on:
  push:
    branches:
      - main

jobs:
  dev_deploy:
    name: Deploy Development Terraform
    concurrency:
      group: "dev-main"
    uses: UKHSA-Internal/devops-github-reusable-workflows/.github/workflows/terraform-plan-apply.yml@v0.6.0
    permissions:
      packages: read
      contents: read
      security-events: write
      statuses: write
      checks: write
      id-token: write
    with:
      environment_name: dev
      execute_terraform_plan: true
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ROLE_NAME: ${{ secrets.AWS_ROLE_NAME }}
      TF_MODULES_SSH_DEPLOY_KEY: ${{ secrets.TF_MODULES_SSH_DEPLOY_KEY }}
