on:
  push:
    branches:
      - main

jobs:
  dev_deploy:
    name: Deploy Development Terraform
    concurrency:
      group: "dev-main"
    uses: UKHSA-Internal/devops-github-reusable-workflows/.github/workflows/terraform-plan-apply.yml@main
    permissions:
      packages: read
      contents: read
      security-events: write
      statuses: write
      checks: write
      id-token: write
    with:
      environment_name: dev
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ROLE_NAME: ${{ secrets.AWS_ROLE_NAME }}
